[general]
import = ["flow_theme.toml"]

[env]
EDITOR = "nvim"
TERMINAL = "alacritty"
JAVA_HOME = "/usr/lib/jvm/default"
BROWSER = "qutebrowser"
VIRTUAL_ENV_DISABLE_PROMPT = "true"
I3BLOCKS_CONTRIB_DIR = "$HOME/.config/i3/i3blocks-contrib"
KOTFILES_PATH = "$HOME/.kotfiles"

[window]
decorations = "Transparent"
